version: "3"
services:
  service-discovery-server:
    build:
      context: ./service-discovery-server/
    container_name: service-discovery-server
    image: service-discovery-server:latest
    ports:
      - "8761:8761"
    networks:
      - opnet
  api-gateway:
    build:
      context: ./api-gateway/
    container_name: api-gateway
    image: api-gateway:latest
    environment:
      - eureka.client.serviceUrl.defaultZone=http://service-discovery-server:8761/eureka/
    ports:
      - "8080:8080"
    depends_on:
      - service-discovery-server
    networks:
      - opnet
networks:
  opnet:
    driver: bridge